// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TMH.API.Data;

#nullable disable

namespace TMH.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260330123044_AddArticleTable")]
    partial class AddArticleTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TMH.Shared.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BookedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("BookingCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Diagnosis")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookingCode")
                        .IsUnique();

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.HasIndex("ScheduleId");

                    b.ToTable("Appointments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookedAt = new DateTime(2026, 3, 21, 8, 0, 0, 0, DateTimeKind.Utc),
                            BookingCode = "APT-2026-00001",
                            Diagnosis = "Viêm xoang hàm hai bên mãn tính",
                            DoctorId = 1,
                            Note = "Khám viêm xoang mãn tính",
                            PatientId = 1,
                            ScheduleId = 1,
                            Status = 5
                        },
                        new
                        {
                            Id = 2,
                            BookedAt = new DateTime(2026, 3, 21, 9, 0, 0, 0, DateTimeKind.Utc),
                            BookingCode = "APT-2026-00002",
                            DoctorId = 1,
                            Note = "Bệnh nhân huỷ do bận việc",
                            PatientId = 4,
                            ScheduleId = 2,
                            Status = 6
                        },
                        new
                        {
                            Id = 3,
                            BookedAt = new DateTime(2026, 3, 21, 10, 0, 0, 0, DateTimeKind.Utc),
                            BookingCode = "APT-2026-00003",
                            DoctorId = 1,
                            Note = "Tái khám sau điều trị amidan",
                            PatientId = 2,
                            ScheduleId = 1,
                            Status = 2
                        },
                        new
                        {
                            Id = 4,
                            BookedAt = new DateTime(2026, 3, 21, 11, 0, 0, 0, DateTimeKind.Utc),
                            BookingCode = "APT-2026-00004",
                            DoctorId = 2,
                            Note = "Nghe kém tai phải",
                            PatientId = 3,
                            ScheduleId = 3,
                            Status = 1
                        },
                        new
                        {
                            Id = 5,
                            BookedAt = new DateTime(2026, 3, 21, 14, 0, 0, 0, DateTimeKind.Utc),
                            BookingCode = "APT-2026-00005",
                            DoctorId = 3,
                            Note = "Trẻ 7 tuổi, viêm tai giữa tái phát",
                            PatientId = 5,
                            ScheduleId = 4,
                            Status = 2
                        });
                });

            modelBuilder.Entity("TMH.Shared.Models.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("nvarchar(220)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Thumbnail")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("TMH.Shared.Models.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Degree")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Doctors", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Degree = "TS",
                            Description = "22 năm kinh nghiệm, BV TMH TW, tốt nghiệp ĐH Tokyo",
                            FullName = "TS.BS. Nguyễn Thanh Vân",
                            IsAvailable = true,
                            Specialty = "Tai Mũi Họng — Phẫu thuật nội soi xoang",
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            Degree = "PGS",
                            Description = "18 năm kinh nghiệm, chuyên thính học, ĐH Melbourne",
                            FullName = "PGS.BS. Trần Minh Linh",
                            IsAvailable = true,
                            Specialty = "Tai Mũi Họng — Thính học & cấy ốc tai",
                            UserId = 3
                        },
                        new
                        {
                            Id = 3,
                            Degree = "TS",
                            Description = "14 năm kinh nghiệm tại BV Nhi Đồng 2, ĐH Seoul",
                            FullName = "TS.BS. Phạm Thị Hương",
                            IsAvailable = true,
                            Specialty = "TMH Nhi — Viêm tai giữa trẻ em",
                            UserId = 4
                        });
                });

            modelBuilder.Entity("TMH.Shared.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppointmentId = 1,
                            Content = "Lịch khám ngày 18/03 lúc 07:00 với BS. Nguyễn Thanh Vân đã xác nhận. Mã: APT-2026-00001",
                            IsRead = true,
                            SentAt = new DateTime(2026, 3, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Đặt lịch thành công",
                            Type = 1,
                            UserId = 6
                        },
                        new
                        {
                            Id = 2,
                            AppointmentId = 1,
                            Content = "Bạn có lịch khám 07:00 ngày 18/03 với BS. Nguyễn Thanh Vân. Đến trước 15 phút.",
                            IsRead = true,
                            SentAt = new DateTime(2026, 3, 17, 8, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Nhắc lịch khám ngày mai",
                            Type = 2,
                            UserId = 6
                        },
                        new
                        {
                            Id = 3,
                            AppointmentId = 2,
                            Content = "Lịch tái khám ngày 18/03 lúc 07:00 đã được lễ tân xác nhận. Mã: APT-2026-00002",
                            IsRead = false,
                            SentAt = new DateTime(2026, 3, 16, 10, 5, 0, 0, DateTimeKind.Utc),
                            Title = "Xác nhận lịch tái khám",
                            Type = 1,
                            UserId = 7
                        },
                        new
                        {
                            Id = 4,
                            AppointmentId = 4,
                            Content = "Lịch khám bé Minh Khôi ngày 18/03 lúc 07:00 với BS. Phạm Thị Hương đang chờ xác nhận.",
                            IsRead = false,
                            SentAt = new DateTime(2026, 3, 17, 14, 5, 0, 0, DateTimeKind.Utc),
                            Title = "Đặt lịch cho bé thành công",
                            Type = 1,
                            UserId = 7
                        },
                        new
                        {
                            Id = 5,
                            AppointmentId = 5,
                            Content = "Lịch khám ngày 18/03 lúc 13:00 với BS. Nguyễn Thanh Vân đã được huỷ theo yêu cầu.",
                            IsRead = false,
                            SentAt = new DateTime(2026, 3, 18, 7, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Lịch khám đã bị huỷ",
                            Type = 3,
                            UserId = 9
                        });
                });

            modelBuilder.Entity("TMH.Shared.Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MedicalHistory")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("RecordCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RecordCode")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Patients", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1990, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Lê Văn An",
                            Gender = "Nam",
                            MedicalHistory = "Viêm mũi dị ứng mãn tính",
                            RecordCode = "BN-2026-0001",
                            UserId = 6
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1985, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Nguyễn Thị Bình",
                            Gender = "Nữ",
                            MedicalHistory = "Viêm amidan tái phát",
                            RecordCode = "BN-2026-0002",
                            UserId = 7
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(2000, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Phạm Văn Cường",
                            Gender = "Nam",
                            MedicalHistory = "Không có tiền sử bệnh",
                            RecordCode = "BN-2026-0003",
                            UserId = 8
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1978, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Hoàng Thị Dung",
                            Gender = "Nữ",
                            MedicalHistory = "Polyp mũi, đã phẫu thuật năm 2020",
                            RecordCode = "BN-2026-0004",
                            UserId = 9
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(2018, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Nguyễn Minh Khôi",
                            Gender = "Nam",
                            MedicalHistory = "Trẻ em, viêm tai giữa tái phát nhiều lần",
                            RecordCode = "BN-2026-0005",
                            UserId = 7
                        });
                });

            modelBuilder.Entity("TMH.Shared.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long>("Amount")
                        .HasColumnType("bigint");

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<string>("BankCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("OrderRef")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RawIpnData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("VnpayResponseCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId")
                        .IsUnique();

                    b.HasIndex("OrderRef");

                    b.HasIndex("TransactionId");

                    b.ToTable("Payments", (string)null);
                });

            modelBuilder.Entity("TMH.Shared.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("GioiTinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTenDem")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("NhomMau")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("SoCCCD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@pktatmuihong.vn",
                            HoTenDem = "Nguyễn Văn",
                            IsActive = true,
                            IsEmailVerified = true,
                            PasswordHash = "$2a$12$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
                            Phone = "0901000001",
                            Role = 1,
                            Ten = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "bsvan@pktatmuihong.vn",
                            HoTenDem = "TS.BS. Nguyễn Thanh",
                            IsActive = true,
                            IsEmailVerified = true,
                            PasswordHash = "$2a$12$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
                            Phone = "0901000002",
                            Role = 2,
                            Ten = "Vân",
                            Username = "bsvan"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "bslinh@pktatmuihong.vn",
                            HoTenDem = "PGS.BS. Trần Minh",
                            IsActive = true,
                            IsEmailVerified = true,
                            PasswordHash = "$2a$12$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
                            Phone = "0901000003",
                            Role = 2,
                            Ten = "Linh",
                            Username = "bslinh"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "bshuong@pktatmuihong.vn",
                            HoTenDem = "TS.BS. Phạm Thị",
                            IsActive = true,
                            IsEmailVerified = true,
                            PasswordHash = "$2a$12$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
                            Phone = "0901000004",
                            Role = 2,
                            Ten = "Hương",
                            Username = "bshuong"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "letanmai@pktatmuihong.vn",
                            HoTenDem = "Trần Thị",
                            IsActive = true,
                            IsEmailVerified = true,
                            PasswordHash = "$2a$12$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
                            Phone = "0901000005",
                            Role = 3,
                            Ten = "Mai",
                            Username = "letanmai"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "levan.an@gmail.com",
                            HoTenDem = "Lê Văn",
                            IsActive = true,
                            IsEmailVerified = false,
                            PasswordHash = "$2a$12$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
                            Phone = "0901000006",
                            Role = 4,
                            Ten = "An",
                            Username = "benhnhan01"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "nguyen.binh@gmail.com",
                            HoTenDem = "Nguyễn Thị",
                            IsActive = true,
                            IsEmailVerified = true,
                            PasswordHash = "$2a$12$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
                            Phone = "0901000007",
                            Role = 4,
                            Ten = "Bình",
                            Username = "benhnhan02"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "pham.cuong@gmail.com",
                            HoTenDem = "Phạm Văn",
                            IsActive = true,
                            IsEmailVerified = true,
                            PasswordHash = "$2a$12$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
                            Phone = "0901000008",
                            Role = 4,
                            Ten = "Cường",
                            Username = "benhnhan03"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "hoang.dung@gmail.com",
                            HoTenDem = "Hoàng Thị",
                            IsActive = true,
                            IsEmailVerified = false,
                            PasswordHash = "$2a$12$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
                            Phone = "0901000009",
                            Role = 4,
                            Ten = "Dung",
                            Username = "benhnhan04"
                        });
                });

            modelBuilder.Entity("TMH.Shared.Models.WorkSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CurrentPatients")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<int>("MaxPatients")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(10);

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<DateTime>("WorkDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.ToTable("WorkSchedules", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CurrentPatients = 1,
                            DoctorId = 1,
                            EndTime = new TimeSpan(0, 11, 0, 0, 0),
                            MaxPatients = 10,
                            StartTime = new TimeSpan(0, 7, 0, 0, 0),
                            WorkDate = new DateTime(2026, 3, 23, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CurrentPatients = 0,
                            DoctorId = 1,
                            EndTime = new TimeSpan(0, 17, 0, 0, 0),
                            MaxPatients = 10,
                            StartTime = new TimeSpan(0, 13, 0, 0, 0),
                            WorkDate = new DateTime(2026, 3, 23, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            CurrentPatients = 3,
                            DoctorId = 2,
                            EndTime = new TimeSpan(0, 11, 0, 0, 0),
                            MaxPatients = 4,
                            StartTime = new TimeSpan(0, 7, 0, 0, 0),
                            WorkDate = new DateTime(2026, 3, 23, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            CurrentPatients = 0,
                            DoctorId = 3,
                            EndTime = new TimeSpan(0, 11, 0, 0, 0),
                            MaxPatients = 10,
                            StartTime = new TimeSpan(0, 7, 0, 0, 0),
                            WorkDate = new DateTime(2026, 3, 23, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            CurrentPatients = 0,
                            DoctorId = 1,
                            EndTime = new TimeSpan(0, 11, 0, 0, 0),
                            MaxPatients = 10,
                            StartTime = new TimeSpan(0, 7, 0, 0, 0),
                            WorkDate = new DateTime(2026, 3, 24, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            CurrentPatients = 4,
                            DoctorId = 2,
                            EndTime = new TimeSpan(0, 11, 0, 0, 0),
                            MaxPatients = 4,
                            StartTime = new TimeSpan(0, 7, 0, 0, 0),
                            WorkDate = new DateTime(2026, 3, 24, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            CurrentPatients = 1,
                            DoctorId = 3,
                            EndTime = new TimeSpan(0, 17, 0, 0, 0),
                            MaxPatients = 8,
                            StartTime = new TimeSpan(0, 13, 0, 0, 0),
                            WorkDate = new DateTime(2026, 3, 24, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            CurrentPatients = 0,
                            DoctorId = 1,
                            EndTime = new TimeSpan(0, 11, 0, 0, 0),
                            MaxPatients = 10,
                            StartTime = new TimeSpan(0, 7, 0, 0, 0),
                            WorkDate = new DateTime(2026, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            CurrentPatients = 2,
                            DoctorId = 2,
                            EndTime = new TimeSpan(0, 11, 0, 0, 0),
                            MaxPatients = 6,
                            StartTime = new TimeSpan(0, 7, 0, 0, 0),
                            WorkDate = new DateTime(2026, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            CurrentPatients = 0,
                            DoctorId = 3,
                            EndTime = new TimeSpan(0, 11, 0, 0, 0),
                            MaxPatients = 10,
                            StartTime = new TimeSpan(0, 7, 0, 0, 0),
                            WorkDate = new DateTime(2026, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("TMH.Shared.Models.Appointment", b =>
                {
                    b.HasOne("TMH.Shared.Models.Doctor", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TMH.Shared.Models.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TMH.Shared.Models.WorkSchedule", "Schedule")
                        .WithMany("Appointments")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("TMH.Shared.Models.Article", b =>
                {
                    b.HasOne("TMH.Shared.Models.Doctor", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("TMH.Shared.Models.Doctor", b =>
                {
                    b.HasOne("TMH.Shared.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TMH.Shared.Models.Notification", b =>
                {
                    b.HasOne("TMH.Shared.Models.Appointment", "Appointment")
                        .WithMany("Notifications")
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TMH.Shared.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Appointment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TMH.Shared.Models.Patient", b =>
                {
                    b.HasOne("TMH.Shared.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TMH.Shared.Models.Payment", b =>
                {
                    b.HasOne("TMH.Shared.Models.Appointment", "Appointment")
                        .WithOne()
                        .HasForeignKey("TMH.Shared.Models.Payment", "AppointmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("TMH.Shared.Models.WorkSchedule", b =>
                {
                    b.HasOne("TMH.Shared.Models.Doctor", "Doctor")
                        .WithMany("WorkSchedules")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("TMH.Shared.Models.Appointment", b =>
                {
                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("TMH.Shared.Models.Doctor", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("WorkSchedules");
                });

            modelBuilder.Entity("TMH.Shared.Models.Patient", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("TMH.Shared.Models.WorkSchedule", b =>
                {
                    b.Navigation("Appointments");
                });
#pragma warning restore 612, 618
        }
    }
}
